
const data = {
    products: [
        {
            name: "Dell XPS 13",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "Dell",
            description: " Ultra-thin and lightweight laptop with excellent performance and stunning display." ,
            base_price: 97999,
            numInStock: 100,
            processor : "Intel Core i7",
            RAM : "16GB",
            Storage : "512GB SSD",
            Battery : "Up to 12 hours",
            display : "13.3-inch FHD InfinityEdge display",
            Operating_System : "Windows 10",
            avg_rating: 4.5,
            numRatings: 100,
            reviews: []

        },
        {
            name: "MacBook Air",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "Apple",
            description: "Sleek and powerful laptop with great battery life and a stunning Retina display." ,
            base_price: 74900,
            numInStock: 100,
            processor : "Apple M1 chip",
            RAM : "8GB",
            Storage : "256GB SSD",
            Battery : "Up to 18 hours",
            display : "13.3-inch Retina display",
            Operating_System : "macOS",
            avg_rating: 4.3,
            numRatings: 100,
            reviews: []

        },
        {
            name: "HP Spectre x360",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "HP",
            description: "Versatile 2-in-1 laptop with a premium design and impressive performance." ,
            base_price: 97999,
            numInStock: 100,
            processor : "Intel Core i7",
            RAM : "16GB",
            Storage : "512GB SSD",
            Battery : "Up to 15 hours",
            display : "13.3-inch 4K OLED touch display",
            Operating_System : "Windows 10",
            avg_rating: 4.6,
            numRatings: 100,
            reviews: []

        },
        {
            name: "Lenovo ThinkPad X1 Carbon",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "Lenovo",
            description: "Business-oriented laptop with robust security features and exceptional durability." ,
            base_price: 105000,
            numInStock: 90,
            processor : "Intel Core i7",
            RAM : "16GB",
            Storage : "1TB SSD",
            Battery : "Up to 19 hours",
            display : "14-inch WQHD display",
            Operating_System : "Windows 10",
            avg_rating: 4.5,
            numRatings: 100,
            reviews: []

        },
        {
            name: "Asus ROG Zephyrus G14",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "Asus",
            description: "High-performance gaming laptop with a compact design and powerful " ,
            base_price: 106990,
            numInStock: 100,
            processor : "AMD Ryzen 9",
            RAM : "16GB",
            Storage : "1TB SSD",
            Battery : "Up to 10 hours",
            display : "14-inch FHD display with 120Hz refresh rate",
            Operating_System : "Windows 10",
            avg_rating: 4.5,
            numRatings: 100,
            reviews: []

        },
        {
            name: "Acer Swift 3",
            images: ["assets/laptop.png"],
     
            category: "Laptops",
            brand: "Acer",
            description: "Lightweight and affordable laptop with decent performance and long" ,
            base_price: 50999,
            numInStock: 100,
            processor : "Intel Core i5",
            RAM : "8GB",
            Storage : "512GB SSD",
            Battery : "Up to 11 hours",
            display : "14-inch Full HD IPS display",
            Operating_System : "Windows 10",
            avg_rating: 4.5,
            numRatings: 100,
            reviews: []

        },
        {
        name: "Sony WH-1000XM4",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Active Noise Cancellation",
        driver : "40mm",
        category: "Headphones",
        brand: "Sony",
        description: "Over-ear wireless headphones with industry-leading noise cancellation, high-resolution audio, and up to 30 hours of battery life." ,
        base_price: 24990,
        numInStock: 100,
        avg_rating: 4.5,
        numRatings: 100,
        reviews: []

        },
        {
        name: "Bose QuietComfort 35 II",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Active Noise Cancellation",
        
        category: "Headphones",
        brand: "Bose",
        description: "Over-ear wireless headphones with renowned noise cancellation" ,
        base_price: 29363,
        numInStock: 100,
        avg_rating: 4.2,
        numRatings: 100,
        reviews: []
    
            },
        {name: "JBL Tune 750BTNC",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Active Noise Cancellation",
        driver : "40mm",
        category: "Headphones",
        brand: "JBL",
        description: "Over-ear wireless headphones with powerful JBL Pure Bass sound, active noise cancellation, and up to 15 hours of battery life" ,
        base_price: 6199,
        numInStock: 100,
        avg_rating: 4.6,
        numRatings: 100,
        reviews: []

        },
        {name: "Sennheiser HD 660 S",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Active Noise Cancellation",
        driver : "38mm",
        category: "Headphones",
        brand: "Sennheiser",
        description: "Open-back dynamic headphones with high-quality audio reproduction, lightweight design, and optimized impedance for a wide range of devices." ,
        base_price: 43990,
        numInStock: 100,
        avg_rating: 4.1,
        numRatings: 100,
        reviews: []

        },
        {name: "Audio-Technica ATH-M50x",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Not applicable (closed-back design)",
        driver : "45mm",
 
        category: "Headphones",
        brand: "ATH",
        description: "Professional studio monitor headphones with exceptional sound clarity, swiveling earcups, and detachable cables." ,
        base_price: 11249,
        numInStock: 100,
        avg_rating: 4.4,
        numRatings: 100,
        reviews: []

        },
        {name: "Beats Solo3 Wireless",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Not applicable",
 
        category: "Headphones",
        brand: "Beats",
        description: "On-ear wireless headphones with Apple W1 chip for seamless connectivity, up to 40 hours of battery life, and sleek design." ,
        base_price: 16990,
        numInStock: 100,
        avg_rating: 3.9,
        numRatings: 100,
        reviews: []

        },
        {name: "Jabra Elite 75t",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Passive Noise Isolation",
 
        category: "Headphones",
        brand: "Jabra",
        description: "True wireless earbuds with secure fit, customizable sound, and up to 28 hours of battery life (including charging case)." ,
        base_price: 14999,
        numInStock: 100,
        avg_rating: 4.6,
        numRatings: 100,
        reviews: []

        },
        {name: "Skullcandy Crusher Evo",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Not applicable",
        driver : "40mm",
        category: "Headphones",
        brand: "Skullcandy",
        description: " Over-ear wireless headphones with adjustable sensory bass, personal sound customization, and long-lasting battery life." ,
        base_price: 12999,
        numInStock: 100,
        avg_rating: 4.2,
        numRatings: 99,
        reviews: []

        },
        {name: "Philips SHP9500",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Not applicable (open-back design)",
        driver : "50mm",
        category: "Headphones",
        brand: "Philips",
        description: "Open-back headphones with hi-fi audio performance, comfortable fit, and detachable cable." ,
        base_price: 6799,
        numInStock: 100,
        avg_rating: 4.4,
        numRatings: 99,
        reviews: []

        },
        {name: "boAt Rockerz 550",
        images: ["assets/headphones.png"],
        Noise_Cancellation : "Passive Noise Isolation",
        driver : "50mm",
        category: "Headphones",
        brand: "boAt",
        description: "Over-ear wireless headphones with immersive sound, powerful bass, and up to 20 hours of playtime." ,
        base_price: 1999,
        numInStock: 100,
        avg_rating: 4.4,
        numRatings: 99,
        reviews: []

        },
        {name: "JBL Flip 5",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "JBL",
        description: "Portable waterproof speaker with powerful sound, up to 12 hours of playtime, and compact design." ,
        base_price: 7999,
        numInStock: 98,
        avg_rating: 4.4,
        numRatings: 99,
        reviews: []

        },
        {name: "Bose SoundLink Revolve+",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth, NFC",
        brand: "Bose",
        description: "Portable 360-degree speaker with deep, loud, and immersive sound, built-in microphone for speakerphone calls, and durable construction." ,
        base_price: 24500,
        numInStock: 98,
        avg_rating: 4.6,
        numRatings: 101,
        reviews: []

        },
        {name: "Sony SRS-XB12",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Sony",
        description: "Compact and portable speaker with EXTRA BASS technology, up to 16 hours of battery life, and waterproof design." ,
        base_price: 3590,
        numInStock: 98,
        avg_rating: 4.6,
        numRatings: 101,
        reviews: []

        },
        {name: "Boat Stone 1000",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth, AUX",
        brand: "Boat",
        description: " Outdoor rugged speaker with powerful sound, IPX5 water and shock resistance, and long-lasting battery life." ,
        base_price: 3499,
        numInStock: 98,
        avg_rating: 3.9,
        numRatings: 101,
        reviews: []

        },
        {name: "Ultimate Ears Wonderboom 2",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Ultimate Ears",
        description: "Portable and waterproof speaker with 360-degree sound, outdoor boost mode, and up to 13 hours of battery life." ,
        base_price: 7499,
        numInStock: 98,
        avg_rating: 4,
        numRatings: 101,
        reviews: []

        },
        {name: "JBL Charge 4",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "JBL",
        description: "Portable waterproof speaker with high-capacity battery, built-in power bank, and JBL Connect+ feature for linking multiple speakers." ,
        base_price: 11499,
        numInStock: 98,
        avg_rating: 4,
        numRatings: 100,
        reviews: []

        },
        {name: "Philips BT50B/00",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Philips",
        description: "Compact and portable speaker with anti-clipping function for distortion-free music, built-in microphone for hands-free calling, and multiple color options." ,
        base_price: 1299,
        numInStock: 98,
        avg_rating: 4,
        numRatings: 100,
        reviews: []

        },
        {name: "Marshall Kilburn II",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Marshall",
        description: "Iconic vintage-style speaker with powerful sound, guitar-inspired carrying strap, and up to 20 hours of playtime." ,
        base_price: 29999,
        numInStock: 98,
        avg_rating: 4.5,
        numRatings: 100,
        reviews: []

        },
        {name: "Xiaomi Mi Outdoor Bluetooth Speaker",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Xiaomi",
        description: " Portable and rugged speaker with IP55 water and dust resistance, up to 20 hours of battery life, and built-in microphone." ,
        base_price: 1399,
        numInStock: 95,
        avg_rating: 4.2,
        numRatings: 100,
        reviews: []
            
        },
        {name: "Harman Kardon Onyx Studio 6",
        images: ["assets/speakers.png"],
        category: "speakers",
        Connectivity_Technology : "Bluetooth",
        brand: "Harman Kardon",
        description: " Premium wireless speaker with studio-quality sound, elegant design, and up to 8 hours of playtime." ,
        base_price: 15999,
        numInStock: 95,
        avg_rating: 4.2,
        numRatings: 100,
        reviews: []

        },
        {name: "Canon EOS 80D",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "DSLR",
        Screen_size : "3 inches",
        video_resolution : "Full HD 1080p",
        brand: "Canon",
        description: "High-performance DSLR camera with a 24.2-megapixel sensor, advanced autofocus system, and built-in Wi-Fi for easy sharing." ,
        base_price: 75999,
        numInStock: 98,
        avg_rating: 4.1,
        numRatings: 100,
        reviews: []

        },
        {name: "Sony Alpha a6400",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "Mirrorless",
        Screen_size : "3 inches",
        video_resolution : "4K Ultra HD",
        brand: "Sony",
        description: "Compact mirrorless camera with a 24.2-megapixel sensor, fast autofocus, real-time eye tracking, and high-speed continuous shooting." ,
        base_price: 83999,
        numInStock: 97,
        avg_rating: 4.4,
        numRatings: 100,
        reviews: []

        },
        {name: "Nikon D5600",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "DSLR",
        Screen_size : "3.2 inches",
        video_resolution : "Full HD 1080p",
        brand: "Nikon",
        description: "Feature-packed DSLR camera with a 24.2-megapixel sensor, vari-angle touchscreen, built-in Wi-Fi, and SnapBridge connectivity." ,
        base_price: 62990,
        numInStock: 94,
        avg_rating: 4.4,
        numRatings: 100,
        reviews: []

        },
        {name: "Fujifilm X-T4",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "Mirrorless",
        Screen_size : "3 inches",
        video_resolution : "4K Ultra HD",
        brand: "Fujifilm",
        description: "Advanced mirrorless camera with a 26.1-megapixel sensor, in-body image stabilization, high-speed shooting, and film simulation modes." ,
        base_price: 144999,
        numInStock: 94,
        avg_rating: 4.7,
        numRatings: 102,
        reviews: []

        },
        {name: "Panasonic Lumix GH5",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "Mirrorless",
        Screen_size : "3.2 inches",
        video_resolution : "4K Ultra HD",
        brand: "Panasonic",
        description: "Professional-grade mirrorless camera with a 20.3-megapixel sensor, dual image stabilization, high-speed autofocus, and V-Log L recording." ,
        base_price: 162990,
        numInStock: 94,
        avg_rating: 4.7,
        numRatings: 102,
        reviews: []

        },
        {name: "Olympus OM-D E-M1 Mark III",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "Mirrorless",
        Screen_size : "3.2 inches",
        video_resolution : "4K Ultra HD",
        brand: "Olympus",
        description: "Weather-sealed mirrorless camera with a 20.4-megapixel sensor, advanced image stabilization, high-speed autofocus, and Live Composite mode." ,
        base_price: 179990,
        numInStock: 94,
        avg_rating: 4.7,
        numRatings: 102,
        reviews: []

        },
        {name: "Canon PowerShot G7 X Mark III",
        images: ["assets/cameras.png"],
        category: "cameras",
        Form_Factor : "Compact",
        Screen_size : "3 inches",
        video_resolution : "4K Ultra HD",
        brand: "Canon",
        description: " Compact digital camera with a 20.1-megapixel sensor, 4.2x optical zoom, tilting touchscreen, and live streaming capabilities." ,
        base_price: 54990,
        numInStock: 91,
        avg_rating: 4.2,
        numRatings: 102,
        reviews: []

        },
        {name: "OnePlus 9 Pro",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "OnePlus",
        description: "Flagship smartphone with a high-refresh-rate display, powerful performance, Hasselblad camera system, and 5G connectivity." ,
        base_price: 64999,
        numInStock: 100,
        processor : "Qualcomm Snapdragon 888",
        RAM : "8GB/12GB",
        Storage : "128GB/256GB",
        Operating_System : "OxygenOS based on Android",
        avg_rating: 4.8,
        numRatings: 100,
        reviews: []
            
        },
        {name: "Samsung Galaxy S21 Ultra",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Samsung",
        description: "Premium flagship phone with a large dynamic AMOLED display, versatile camera setup, S Pen support, and 5G capability." ,
        base_price: 105999,
        numInStock: 101,
        processor : "Exynos 2100 / Qualcomm Snapdragon 888",
        RAM : "12GB/16GB",
        Storage : "128GB/256GB/512GB",
        Operating_System : "One UI based on Android",
        avg_rating: 4.8,
        numRatings: 100,
        reviews: []

        },
        {name: "Apple iPhone 13 Pro Max",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Apple",
        description: "High-end iPhone model with an improved Super Retina XDR display, advanced camera system, powerful performance, and Face ID." ,
        base_price: 129900,
        numInStock: 101,
        processor : "Apple A15 Bionic",
        RAM : "6GB",
        Storage : "128GB/256GB/512GB/1TB",
        Operating_System : "iOS",
        avg_rating: 4.8,
        numRatings: 100,
        reviews: []

        },
        {name: "Xiaomi Mi 11X Pro",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Xiaomi",
        description: "Flagship-level smartphone with a 120Hz AMOLED display, powerful camera system, fast charging, and 5G support." ,
        base_price: 39999,
        numInStock: 90,
        processor : "Qualcomm Snapdragon 888",
        RAM : "8GB",
        Storage : "128GB/256GB",
        Operating_System : "MIUI based on Android",
        avg_rating: 4.3,
        numRatings: 100,
        reviews: []

        },
        {name: "Vivo X60 Pro+",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Vivo",
        description: "Premium smartphone with a gimbal stabilization camera system, AMOLED display, powerful performance, and 5G connectivity." ,
        base_price: 69990,
        numInStock: 92,
        processor : "Qualcomm Snapdragon 888",
        RAM : "12GB",
        Storage : " 256GB",
        Operating_System : " Funtouch OS based on Android",
        avg_rating: 4.3,
        numRatings: 100,
        reviews: []

        },
        {name: "Realme GT 5G",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Realme",
        description: "High-performance 5G smartphone with a 120Hz AMOLED display, triple-camera setup, and fast charging capabilities." ,
        base_price: 37999,
        numInStock: 92,
        processor : "Qualcomm Snapdragon 888",
        RAM : "8GB/12GB",
        Storage : "128GB/256GB",
        Operating_System : "Realme UI based on Android",
        avg_rating: 4.3,
        numRatings: 100,
        reviews: []

        },
        {name: "Google Pixel 6 Pro",
        images: ["assets/smartphones.png"],
        category: "smartphones",
        brand: "Google",
        description: "Flagship Google Pixel phone with advanced computational photography features, high-refresh-rate display, and 5G capability." ,
        base_price: 85999,
        numInStock: 94,
        processor : "Google Tensor",
        RAM : " 12GB",
        Storage : "128GB/256GB/512GB",
        Operating_System : "Android with Google apps and services",
        avg_rating: 4.3,
        numRatings: 100,
        reviews: []

        }


        
                
        

        
    ]

}
export default data